import turtle
turtle.hideturtle()
turtle.up()
turtle.width(8)
turtle.setposition(55, 3)
turtle.down()
turtle.color('LightSkyBlue')
turtle.right(80)
turtle.fd(80)
turtle.left(80)
turtle.up()
turtle.setposition(95, 3)
turtle.down()
turtle.color('LightSkyBlue')
turtle.right(90)
turtle.fd(75)
turtle.left(90)
turtle.up()
turtle.setposition(135, 3)
turtle.down()
turtle.color('LightSkyBlue')
turtle.right(100)
turtle.fd(80)
turtle.left(100)
turtle.up()
turtle.setposition(30, -20)
turtle.down()
turtle.color('LightSkyBlue')
turtle.fd(130)
turtle.up()
turtle.setposition(37, -40)
turtle.down()
turtle.color('LightSkyBlue')
turtle.fd(118)
turtle.color('SteelBlue')
turtle.up()
turtle.setposition(-30, 30)
turtle.down()
turtle.fd(40)
turtle.right(70)
turtle.fd(30)
turtle.left(70)
turtle.fd(150)
turtle.right(110)
turtle.fd(85)
turtle.left(110)
turtle.right(180)
turtle.fd(92)
turtle.left(180)
turtle.up()
turtle.left(110)
turtle.fd(25)
turtle.down()
turtle.fd(60)
turtle.right(110)
turtle.up()
turtle.right(70)
turtle.fd(85)
turtle.left(70)
turtle.down()
turtle.right(70)
turtle.fd(20)
turtle.left(70)
turtle.fd(83)
turtle.fillcolor('SteelBlue')
turtle.begin_fill()
turtle.color('SteelBlue')
turtle.up()
turtle.setposition(70, -128)
turtle.down()
turtle.circle(8)
turtle.end_fill()
turtle.begin_fill()
turtle.color('SteelBlue')
turtle.up()
turtle.setposition(130, -128)
turtle.down()
turtle.circle(8)
turtle.end_fill()
turtle.done()
